### PR TITLE
Updated YAML files to pass lint

### LINKED ISSUE #10: Address YAML lint errors
In the GitHub Action [SLATE Deployment #216](https://github.com/slateci/atlas-squid/runs/7043165434?check_suite_focus=true) several YAML lint errors were produced and are displayed below. Adding @sthapa  and @LincolnBryant  as watchers.
```shell
======================
= Linting YAML files =
======================
...
Error: -squid-aglt2-2/values.yaml:22:23: [error] trailing spaces (trailing-spaces)
...
Error: -squid-aglt2-2/values.yaml:26:15: [error] trailing spaces (trailing-spaces)
...
Error: -squid-aglt2-2/values.yaml:34:1: [error] too many blank lines (1 > 0) (empty-lines)
...
Error: -squid-mwt2-iu-test-1/values.yaml:13:1: [error] duplication of key "ImageTag" in mapping (key-duplicates)
...
Error: -squid-mwt2-iu-1/instance.yaml:2:1: [error] too many blank lines (1 > 0) (empty-lines)
...
Error: -squid-mwt2-iu-test-1/instance.yaml:5:31: [error] no new line character at the end of file (new-line-at-end-of-file)
...
Error: -squid-mwt2-uiuc-1/instance.yaml:5:31: [error] no new line character at the end of file (new-line-at-end-of-file)
...
Error: -squid-uchicago-prod-1/instance.yaml:5:31: [error] no new line character at the end of file (new-line-at-end-of-file)
...
Error: -squid-uchicago-prod-3/instance.yaml:5:31: [error] no new line character at the end of file (new-line-at-end-of-file)
...
Error: -squid-uchicago-prod2-1/instance.yaml:5:31: [error] no new line character at the end of file (new-line-at-end-of-file)
...
Error: -squid-uchicago-river-v2/instance.yaml:5:31: [error] no new line character at the end of file (new-line-at-end-of-file)
Error: Process completed with exit code 1.
```

### PR DESCRIPTION
**Pull request by adamhgriffith-uofu**
See #10 for more details.

### CODE REVIEW

**Comment by LincolnBryant** [comment]
This will cause a lot of simultaneous restarts I expect.. We might have to apply this one at a time.

**Comment by adamhgriffith-uofu** [comment]
Ah good point. I could also abort the GitHub action post-merge so it doesn't actually do anything to the instances?

**Comment by adamhgriffith-uofu** [comment]
Ok. @sthapa @LincolnBryant, I loosened the YAML lint rules and we are down to just the one file change.

**Review by LincolnBryant — APPROVED** [review]
Approve ImageTag change to Instance.

**Pull request merged**
